### ISSUE TITLE
inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by WARZZ-CREATOR55** [Mr4FX/HULK#3]
Hello bro, when I tried to install ur tool on termux, I did every command to install it but then it didn't work and it said "File "/data/data/com.termux/files/home/Hulk-ddos-attack/hulk.py", line 14358
    headers_useragents.append('Lynx/2.8.5rel.5 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/0.9.7d')
TabError: inconsistent use of tabs and spaces in indentation"
Can u please help me fix it?
Thanks.

**Comment by Mr4FX** [comment]
hello,
please make sure that your python version is the same version that is required
and check if requests is installed
thanks
